import { CategoryKey } from './types';

export const wordsDB: Record<CategoryKey, [string, string][]> = {
  players: [
    ["Messi", "ميسي"], ["Ronaldo", "رونالدو"], ["Neymar", "نيمار"], ["Mbappe", "مبابي"],
    ["Haaland", "هالاند"], ["De Bruyne", "دي بروين"], ["Benzema", "بنزيما"], ["Modric", "مودريتش"],
    ["Salah", "صلاح"], ["Kane", "كين"], ["Lewandowski", "ليفاندوفسكي"], ["Griezmann", "جريزمان"],
    ["Suarez", "سواريز"], ["Ramos", "راموس"], ["Van Dijk", "فان دايك"], ["Kroos", "كروس"],
    ["Casemiro", "كاسيميرو"], ["Bruno Fernandes", "برونو فيرنانديز"], ["Son Heung-min", "سون هيونج مين"],
    ["Vinicius Jr", "فينيسيوس جونيور"], ["Rodrygo", "رودريجو"], ["Pedri", "بيدري"], ["Gavi", "جافي"],
    ["Bellingham", "بيلينجهام"], ["Foden", "فودين"], ["Saka", "ساكا"], ["Rashford", "راشفورد"],
    ["Mane", "ماني"], ["Mahrez", "محرز"], ["Ibrahimovic", "إبراهيموفيتش"], ["Iniesta", "إنييستا"],
    ["Xavi", "تشافي"], ["Casillas", "كاسياس"], ["Buffon", "بوفون"], ["Ronaldinho", "رونالدينيو"],
    ["Zidane", "زيدان"], ["Ronaldo Nazario", "رونالدو نازاريو"], ["Pele", "بيليه"], ["Maradona", "مارادونا"],
    ["Cruyff", "كرويف"], ["Beckenbauer", "بيكنباور"], ["Beckham", "بيكهام"], ["Henry", "هنري"],
    ["Drogba", "دروجبا"], ["Eto'o", "إيتو"], ["Elneny", "النني"], ["Trezeguet", "تريزيجيه"],
    ["Marmoush", "مرموش"], ["Mostafa Mohamed", "مصطفى محمد"], ["Hegazi", "الحجازي"],
    ["Ahmed Fathy", "أحمد فتحي"], ["Emad Meteb", "عماد متعب"], ["Hossam Hassan", "حسام حسن"],
    ["Abou Trika", "أبو تريكة"], ["Mido", "ميدو"], ["El Khatib", "الخطيب"], ["Ali Gabr", "علي جبر"],
    ["Sterling", "ستيرلينج"], ["Grealish", "جريليش"], ["Rice", "رايس"], ["Pogba", "بوجبا"],
    ["Kante", "كانتي"], ["Dembele", "ديمبلي"], ["De Jong", "دي يونج"], ["Kimmich", "كيميش"],
    ["Muller", "مولر"], ["Neuer", "نوير"], ["Cavani", "كافاني"], ["Di Maria", "دي ماريا"],
    ["Aguero", "أجويرو"], ["Falcao", "فالكاو"], ["James Rodriguez", "خامس رودريجيز"],
    ["Alexis Sanchez", "أليكسيس سانشيز"], ["Robben", "روبن"], ["Ribery", "ريبيري"],
    ["Busquets", "بوسكيتس"], ["Puyol", "بويول"], ["Fabregas", "فابريجاس"], ["Torres", "توريس"],
    ["Villa", "فيا"], ["Courtois", "كورتوا"], ["Alisson", "أليسون"], ["Ederson", "إيدرسون"],
    ["Ter Stegen", "تير شتيجن"], ["Hakimi", "حكيمي"], ["Theo Hernandez", "ثيو هيرنانديز"],
    ["Trent Alexander-Arnold", "ترينت ألكسندر أرنولد"], ["Joao Cancelo", "جواو كانسيلو"],
    ["Marquinhos", "ماركينيوس"], ["Varane", "فاران"], ["Rudiger", "روديجر"],
    ["Ruben Dias", "روبن دياز"], ["John Stones", "جون ستونز"], ["Odegaard", "أوديجارد"],
    ["Pulisic", "بوليسيتش"], ["Lamine Yamal", "لامين يامال"], ["Musiala", "موسيالا"],
    ["Wirtz", "فيرتز"], ["Valverde", "فالفيردي"], ["Camavinga", "كامافينجا"],
    ["Enzo Fernandez", "إنزو فيرنانديز"], ["Julian Alvarez", "خوليان ألفاريز"],
    ["Cole Palmer", "كول بالمر"], ["Ahmed Hassan", "أحمد حسن"], ["Wael Gomaa", "وائل جمعة"]
  ],
  food: [
    ["Pizza", "بيتزا"], ["Burger", "برجر"], ["Sushi", "سوشي"], ["Pasta", "باستا"],
    ["Shawarma", "شاورما"], ["Tacos", "تاكوس"], ["Ice Cream", "آيس كريم"], ["Koshary", "كشري"],
    ["Crepe", "كريب"], ["Falafel", "فلافل"], ["Hummus", "حمص"], ["Kebab", "كباب"],
    ["Molokhia", "ملوخية"], ["Ful Medames", "فول مدمس"], ["Ta'meya", "طعمية"], ["Mahshi", "محشي"],
    ["Fattah", "فتة"], ["Sayadeya", "صيادية"], ["Kofta", "كفتة"], ["Shish Tawook", "شيش طاووق"],
    ["Ramen", "رامن"], ["Pho", "فو"], ["Dumplings", "دمبلنجز"], ["Fried Rice", "أرز مقلي"],
    ["Spring Rolls", "سبرنج رول"], ["Croissant", "كرواسون"], ["Pancakes", "بان كيك"],
    ["Waffles", "وافل"], ["Donuts", "دونات"], ["Cheesecake", "تشيز كيك"], ["Tiramisu", "تيراميسو"],
    ["Baklava", "بقلاوة"], ["Basbousa", "بسبوسة"], ["Kunafa", "كنافة"], ["Om Ali", "أم علي"],
    ["Rice Pudding", "أرز باللبن"], ["Popcorn", "فشار"], ["Nachos", "ناتشوز"], ["Fries", "بطاطس مقلية"],
    ["Hot Dog", "هوت دوج"], ["Sandwich", "ساندويتش"], ["Steak", "ستيك"], ["Grilled Fish", "سمك مشوي"],
    ["Lasagna", "لازانيا"], ["Ravioli", "رافيولي"], ["Fried Chicken", "فراخ مقلية"],
    ["Chicken Wings", "أجنحة دجاج"], ["BBQ Ribs", "أضلاع مشوية"], ["Paella", "بايلا"],
    ["Risotto", "ريزوتو"], ["Gnocchi", "نيوكي"], ["Curry", "كاري"], ["Biryani", "برياني"],
    ["Samosa", "سمبوسة"], ["Naan", "نان"], ["Tikka Masala", "تيكا ماسالا"], ["Pad Thai", "باد تاي"],
    ["Dim Sum", "دمسم"], ["Bao Buns", "باو بن"], ["Ceviche", "سيفيتشي"], ["Guacamole", "جواكامولي"],
    ["Quesadilla", "كساديا"], ["Burrito", "بوريتو"], ["Enchilada", "إنشيلادا"], ["Churros", "تشوروس"],
    ["Gelato", "جيلاتو"], ["Macaron", "ماكارون"], ["Fondue", "فوندو"], ["Ratatouille", "راتاتوي"],
    ["Goulash", "جولاش"], ["Schnitzel", "شنيتزل"], ["Pretzel", "بريتزل"], ["Bratwurst", "براتورست"],
    ["Hawawshi", "حواوشي"], ["Feteer", "فطير"], ["Roz Bel Laban", "رز بلبن"], ["Sobia", "سوبيا"],
    ["Karkade", "كركديه"], ["Asab", "عصب"], ["Shakshuka", "شكشوكة"], ["Fesikh", "فسيخ"],
    ["Zalabya", "زلابية"], ["Grilled Shrimp", "جمبري مشوي"], ["Calamari", "كالاماري"],
    ["Lobster", "استاكوزا"], ["Crab Cakes", "كرات السلطعون"], ["Clam Chowder", "شوربة المحار"],
    ["Miso Soup", "شوربة ميسو"], ["Tempura", "تمبورا"], ["Katsu Curry", "كاتسو كاري"],
    ["Bibimbap", "بيبيمباب"], ["Kimchi", "كيمتشي"], ["Bulgogi", "بولجوجي"], ["Tteokbokki", "توك بوكي"],
    ["Manakish", "مناقيش"], ["Fattoush", "فتوش"], ["Tabbouleh", "تبولة"], ["Baba Ghanoush", "بابا غنوج"],
    ["Kibbeh", "كبة"], ["Dubai Chocolate", "شوكولاتة دبي"], ["Chocolate Kunafa", "كنافة شوكولاتة"],
    ["Boba Tea", "بابل تي"], ["Smash Burger", "سماش برجر"], ["Croffle", "كروفل"],
    ["Loaded Fries", "بطاطس محملة"], ["Freakshake", "فريك شيك"], ["Dalgona Coffee", "قهوة دالجونا"],
    ["Birria Tacos", "تاكوس بيريا"]
  ],
  places: [
    ["Pyramids", "الأهرامات"], ["Eiffel Tower", "برج إيفل"], ["Dubai", "دبي"], ["London", "لندن"],
    ["Tokyo", "طوكيو"], ["New York", "نيويورك"], ["Rome", "روما"], ["Colosseum", "الكولوسيوم"],
    ["Big Ben", "بيج بن"], ["Statue of Liberty", "تمثال الحرية"], ["Great Wall of China", "سور الصين العظيم"],
    ["Taj Mahal", "تاج محل"], ["Sydney Opera House", "دار أوبرا سيدني"], ["Niagara Falls", "شلالات نياجرا"],
    ["Grand Canyon", "جراند كانيون"], ["Sahara Desert", "الصحراء الكبرى"], ["Nile River", "نهر النيل"],
    ["Petra", "البتراء"], ["Machu Picchu", "ماتشو بيتشو"], ["Christ the Redeemer", "تمثال المسيح الفادي"],
    ["Burj Khalifa", "برج خليفة"], ["Sphinx", "أبو الهول"], ["Luxor Temple", "معبد الأقصر"],
    ["Karnak Temple", "معبد الكرنك"], ["Abu Simbel", "أبو سمبل"], ["Alexandria Library", "مكتبة الإسكندرية"],
    ["Khan El Khalili", "خان الخليلي"], ["Cairo Tower", "برج القاهرة"], ["Red Sea", "البحر الأحمر"],
    ["Sharm El Sheikh", "شرم الشيخ"], ["Hurghada", "الغردقة"], ["Siwa Oasis", "واحة سيوة"],
    ["Venice", "البندقية"], ["Paris", "باريس"], ["Barcelona", "برشلونة"], ["Amsterdam", "أمستردام"],
    ["Berlin", "برلين"], ["Vienna", "فيينا"], ["Prague", "براغ"], ["Istanbul", "إسطنبول"],
    ["Athens", "أثينا"], ["Santorini", "سانتوريني"], ["Mecca", "مكة"], ["Medina", "المدينة المنورة"],
    ["Jerusalem", "القدس"], ["Marrakech", "مراكش"], ["Casablanca", "الدار البيضاء"],
    ["Cape Town", "كيب تاون"], ["Victoria Falls", "شلالات فيكتوريا"], ["Mount Kilimanjaro", "جبل كليمنجارو"],
    ["Bali", "بالي"], ["Maldives", "المالديف"], ["Singapore", "سنغافورة"], ["Hong Kong", "هونج كونج"],
    ["Shanghai", "شنغهاي"], ["Beijing", "بكين"], ["Seoul", "سيؤول"], ["Bangkok", "بانكوك"],
    ["Kuala Lumpur", "كوالالمبور"], ["Mumbai", "مومباي"], ["Rio de Janeiro", "ريو دي جانيرو"],
    ["Buenos Aires", "بوينس آيرس"], ["Los Angeles", "لوس أنجلوس"], ["Las Vegas", "لاس فيجاس"],
    ["Miami", "ميامي"], ["Chicago", "شيكاجو"], ["Toronto", "تورونتو"], ["Moscow", "موسكو"],
    ["Red Square", "الساحة الحمراء"], ["Amazon Rainforest", "غابات الأمازون"], ["Iguazu Falls", "شلالات إجوازو"],
    ["Mount Everest", "جبل إيفرست"], ["Swiss Alps", "جبال الألب السويسرية"], ["Dead Sea", "البحر الميت"],
    ["Golden Gate Bridge", "جسر البوابة الذهبية"], ["Hollywood Sign", "لافتة هوليوود"],
    ["Central Park", "سنترال بارك"], ["Times Square", "تايمز سكوير"], ["White House", "البيت الأبيض"],
    ["Kremlin", "الكرملين"], ["Acropolis", "الأكروبوليس"], ["Stonehenge", "ستونهنج"],
    ["Vatican City", "الفاتيكان"], ["Notre Dame", "نوتردام"], ["Louvre Museum", "متحف اللوفر"],
    ["Sagrada Familia", "ساجرادا فاميليا"], ["Alhambra", "قصر الحمراء"],
    ["Buckingham Palace", "قصر باكنجهام"], ["Antarctica", "القارة القطبية الجنوبية"]
  ],
  movies: [
    ["Kirah Wel Genn", "كيرة والجن"], ["Restart", "ريستارت"], ["Serr El Bate", "سره الباتع"],
    ["Sayed El Nas", "سيد الناس"], ["Brens", "برنس"], ["Taj", "تاج"], ["Hogan", "هوجان"],
    ["Profile", "بروفايل"], ["Nasl El Aghrab", "نسل الأغراب"], ["Molouk El Gadaana", "ملوك الجدعنة"],
    ["Be 100 Wesh", "بـ100 وش"], ["Moussa", "موسى"], ["Bedon Sabek Enzar", "بدون سابق إنذار"],
    ["El Ekhtiar 3", "الاختيار 3"], ["Welad Rizk El Madi", "ولاد رزق الماضي"],
    ["Faten Amal Harbi", "فاتن أمل حربي"], ["Gazirat Ghamam", "جزيرة غمام"], ["Beit El Roby", "بيت الروبي"],
    ["El Hashashin", "الحشاشين"], ["Joddar", "جودر"], ["Esm Mo2aqat", "اسم مؤقت"],
    ["El Maddah", "المداح"], ["Welad El Shams", "ولاد الشمس"], ["Taht El Wesaya", "تحت الوصاية"],
    ["Aho Da Elly Sar", "أهو ده اللي صار"], ["Pablo", "بابلو"], ["Tariki", "طريقي"],
    ["El Mashwar", "المشوار"], ["Shahd El Malika", "شهد الملكة"], ["Welad Rizk 3", "ولاد رزق 3: القاضية"],
    ["El Kelab El Sabaa", "الكلاب السبعة"], ["Barshama", "برشامة"], ["Seko Seko", "سيكو سيكو"],
    ["El Harifa 2", "الحريفة 2: الريمونتادا"], ["X Merati", "اكس مراتي"],
    ["El Hena Elly Ana Fih", "الهنا اللي أنا فيه"], ["Dae Serat Ahl El Dae", "ضي: سيرة أهل الضي"],
    ["Lam Shamseya", "لام شمسية"], ["Gaafar El Omda 2", "جعفر العمدة 2"], ["Cobra", "كوبرا"],
    ["Ard El Nefaq 2", "أرض النفاق 2"], ["El Rakoon", "الراكون"], ["Ramadan Kareem 3", "رمضان كريم 3"],
    ["Qesset Madina", "قصة مدينة"], ["Shoghl Fanadeq", "شغل فنادق"], ["Atabat El Bahga", "عتبات البهجة"],
    ["Hakim Series", "حكيم"], ["Moharib", "محارب"], ["El Amir", "الأمير"], ["Farawla", "فراولة"],
    ["Kamel El Adad 2", "كامل العدد 2"], ["Lahzet Ghadab", "لحظة غضب"]
  ],
  games: [
    ["GTA V", "جي تي إيه 5"], ["Minecraft", "ماين كرافت"], ["PUBG", "ببجي"], ["FIFA", "فيفا"],
    ["Valorant", "فالورانت"], ["Call of Duty", "كول أوف ديوتي"], ["Fortnite", "فورتنايت"],
    ["League of Legends", "ليج أوف ليجيندز"], ["Roblox", "روبلوكس"], ["Among Us", "أمونج أس"],
    ["Apex Legends", "أبيكس ليجيندز"], ["Overwatch", "أوفرواتش"], ["Counter-Strike", "كاونتر سترايك"],
    ["Rainbow Six Siege", "رينبو سيكس سييج"], ["Rocket League", "روكيت ليج"], ["The Sims", "ذا سيمز"],
    ["Red Dead Redemption", "ريد ديد ريدمبشن"], ["The Witcher 3", "ذا ويتشر 3"],
    ["Cyberpunk 2077", "سايبربانك 2077"], ["Elden Ring", "إلدن رينج"], ["Dark Souls", "دارك سولز"],
    ["God of War", "جود أوف وور"], ["The Last of Us", "ذا لاست أوف أس"], ["Uncharted", "أنتشارتد"],
    ["Horizon Zero Dawn", "هورايزن زيرو داون"], ["Assassin's Creed", "أساسنز كريد"],
    ["Far Cry", "فار كراي"], ["Watch Dogs", "واتش دوجز"], ["Resident Evil", "ريزدنت إيفل"],
    ["Silent Hill", "سايلنت هيل"], ["Mortal Kombat", "مورتال كومبات"], ["Street Fighter", "ستريت فايتر"],
    ["Tekken", "تيكن"], ["Super Mario", "سوبر ماريو"], ["Zelda", "زيلدا"], ["Pokemon", "بوكيمون"],
    ["Animal Crossing", "أنيمال كروسينج"], ["Splatoon", "سبلاتون"], ["Kirby", "كيربي"],
    ["Sonic", "سونيك"], ["Crash Bandicoot", "كراش بانديكوت"], ["Spyro", "سبايرو"],
    ["Metal Gear Solid", "ميتال جير سوليد"], ["Halo", "هيلو"], ["Gears of War", "جيرز أوف وور"],
    ["Forza", "فورتزا"], ["Need for Speed", "نيد فور سبيد"], ["Gran Turismo", "جران توريزمو"],
    ["eFootball", "إي فوتبول"], ["Clash of Clans", "كلاش أوف كلانز"], ["Clash Royale", "كلاش رويال"],
    ["Candy Crush", "كاندي كراش"], ["Subway Surfers", "صب واي سيرفرز"], ["Temple Run", "تمبل ران"],
    ["Free Fire", "فري فاير"], ["Brawl Stars", "براول ستارز"], ["Genshin Impact", "جينشين إمباكت"],
    ["Honkai Star Rail", "هونكاي ستار ريل"], ["World of Warcraft", "وورلد أوف ووركرافت"],
    ["Dota 2", "دوتا 2"], ["StarCraft", "ستار كرافت"], ["Diablo", "ديابلو"],
    ["Hearthstone", "هارثستون"], ["Terraria", "تيراريا"], ["Stardew Valley", "ستارديو فالي"],
    ["Fall Guys", "فول جايز"], ["It Takes Two", "إت تيكس تو"], ["Hades", "هيديز"],
    ["Celeste", "سيليست"], ["Hollow Knight", "هولو نايت"], ["Valheim", "فالهايم"],
    ["Palworld", "بال وورلد"], ["Baldur's Gate 3", "بالدرز جيت 3"], ["Helldivers 2", "هيل دايفرز 2"],
    ["Sea of Thieves", "سي أوف ثيفز"], ["Destiny 2", "ديستني 2"], ["Warframe", "وور فريم"],
    ["Mobile Legends", "موبايل ليجندز"], ["Wild Rift", "وايلد ريفت"], ["Slither.io", "سلذر أيو"],
    ["Plants vs Zombies", "بلانتس فيرسس زومبيز"], ["Angry Birds", "أنجري بيردز"], ["8 Ball Pool", "8 بول بول"]
  ],
  animals: [
    ["Lion", "أسد"], ["Tiger", "نمر"], ["Elephant", "فيل"], ["Falcon", "صقر"],
    ["Dolphin", "دولفين"], ["Cheetah", "فهد"], ["Wolf", "ذئب"], ["Eagle", "نسر"],
    ["Bear", "دب"], ["Giraffe", "زرافة"], ["Zebra", "حمار وحشي"], ["Hippo", "فرس النهر"],
    ["Rhino", "وحيد القرن"], ["Crocodile", "تمساح"], ["Kangaroo", "كنغر"], ["Koala", "كوالا"],
    ["Panda", "باندا"], ["Gorilla", "غوريلا"], ["Chimpanzee", "شمبانزي"], ["Monkey", "قرد"],
    ["Camel", "جمل"], ["Fox", "ثعلب"], ["Deer", "أيل"], ["Rabbit", "أرنب"],
    ["Squirrel", "سنجاب"], ["Hedgehog", "قنفذ"], ["Otter", "قضاعة"], ["Beaver", "قندس"],
    ["Raccoon", "راكون"], ["Skunk", "ظربان"], ["Bat", "خفاش"], ["Owl", "بومة"],
    ["Peacock", "طاووس"], ["Parrot", "ببغاء"], ["Flamingo", "فلامنجو"], ["Penguin", "بطريق"],
    ["Ostrich", "نعامة"], ["Swan", "بجعة"], ["Duck", "بطة"], ["Pelican", "بجع"],
    ["Shark", "قرش"], ["Whale", "حوت"], ["Octopus", "أخطبوط"], ["Jellyfish", "قنديل البحر"],
    ["Starfish", "نجم البحر"], ["Seahorse", "حصان البحر"], ["Turtle", "سلحفاة"], ["Snake", "ثعبان"],
    ["Lizard", "سحلية"], ["Chameleon", "حرباء"], ["Iguana", "إجوانا"], ["Frog", "ضفدع"],
    ["Toad", "ضفدع الطين"], ["Butterfly", "فراشة"], ["Bee", "نحلة"], ["Ant", "نملة"],
    ["Spider", "عنكبوت"], ["Scorpion", "عقرب"], ["Snail", "حلزون"], ["Hyena", "ضبع"],
    ["Jackal", "ابن آوى"], ["Leopard", "نمر مرقط"], ["Jaguar", "جاجوار"], ["Puma", "بوما"],
    ["Lynx", "وشق"], ["Wolverine", "ولفرين"], ["Meerkat", "ميركات"], ["Sloth", "كسلان"],
    ["Armadillo", "أرماديلو"], ["Platypus", "منقار البط"], ["Walrus", "فظ"], ["Seal", "فقمة"],
    ["Sea Lion", "أسد البحر"], ["Orca", "الحوت القاتل"], ["Manatee", "خروف البحر"],
    ["Buffalo", "جاموس"], ["Bison", "بيسون"], ["Antelope", "ظبي"], ["Gazelle", "غزال"],
    ["Wildebeest", "النو"], ["Warthog", "خنزير بري"], ["Crow", "غراب"], ["Pigeon", "حمامة"],
    ["Sparrow", "عصفور"], ["Hummingbird", "طائر الطنان"], ["Woodpecker", "نقار الخشب"],
    ["Toucan", "طوقان"], ["Vulture", "رخمة"], ["Condor", "كوندور"], ["Stork", "لقلق"],
    ["Heron", "مالك الحزين"], ["Anteater", "آكل النمل"], ["Aardvark", "أردفارك"],
    ["Tapir", "تابير"], ["Okapi", "أوكابي"], ["Capybara", "كابيبارا"]
  ],
  jobs: [
    ["Doctor", "دكتور"], ["Teacher", "مدرس"], ["Engineer", "مهندس"], ["Pilot", "طيار"],
    ["Chef", "شيف"], ["Nurse", "ممرضة"], ["Lawyer", "محامي"], ["Police Officer", "ضابط شرطة"],
    ["Firefighter", "رجل إطفاء"], ["Farmer", "فلاح"], ["Fisherman", "صياد"],
    ["Electrician", "كهربائي"], ["Plumber", "سباك"], ["Carpenter", "نجار"],
    ["Painter", "رسام"], ["Photographer", "مصور"], ["Journalist", "صحفي"], ["Actor", "ممثل"],
    ["Singer", "مطرب"], ["Dancer", "راقص"], ["Athlete", "رياضي"], ["Soldier", "جندي"],
    ["Judge", "قاضي"], ["Accountant", "محاسب"], ["Architect", "مهندس معماري"],
    ["Dentist", "طبيب أسنان"], ["Pharmacist", "صيدلي"], ["Veterinarian", "طبيب بيطري"],
    ["Scientist", "عالم"], ["Astronaut", "رائد فضاء"], ["Taxi Driver", "سائق تاكسي"],
    ["Bus Driver", "سائق أتوبيس"], ["Mechanic", "ميكانيكي"], ["Barber", "حلاق"],
    ["Tailor", "ترزي"], ["Baker", "خباز"], ["Butcher", "جزار"], ["Waiter", "جرسون"],
    ["Bartender", "بارمان"], ["Receptionist", "موظف استقبال"], ["Secretary", "سكرتيرة"],
    ["Manager", "مدير"], ["Salesman", "بائع"], ["Cashier", "كاشير"], ["Security Guard", "حارس أمن"],
    ["Cleaner", "عامل نظافة"], ["Gardener", "بستاني"], ["Librarian", "أمين مكتبة"],
    ["Translator", "مترجم"], ["Programmer", "مبرمج"], ["Graphic Designer", "مصمم جرافيك"],
    ["Web Developer", "مطور مواقع"], ["Data Analyst", "محلل بيانات"],
    ["Real Estate Agent", "سمسار عقارات"], ["Flight Attendant", "مضيف طيران"],
    ["Tour Guide", "مرشد سياحي"], ["Fashion Designer", "مصمم أزياء"],
    ["Interior Designer", "مصمم ديكور"], ["Content Creator", "صانع محتوى"],
    ["Influencer", "مؤثر"], ["YouTuber", "يوتيوبر"], ["Social Media Manager", "مسؤول سوشيال ميديا"],
    ["UI/UX Designer", "مصمم واجهات"], ["Delivery Captain", "كابتن توصيل"],
    ["Video Editor", "مونتير"], ["Digital Marketing Specialist", "أخصائي تسويق رقمي"],
    ["E-commerce Seller", "بائع أونلاين"], ["Freelancer", "فريلانسر"],
    ["Podcaster", "بودكاستر"], ["App Developer", "مطور تطبيقات"], ["Barista", "باريستا"],
    ["Personal Trainer", "مدرب شخصي"], ["Makeup Artist", "فنان مكياج"]
  ],
  singers: [
    ["Amr Diab", "عمرو دياب"], ["Tamer Hosny", "تامر حسني"], ["Mohamed Ramadan", "محمد رمضان"],
    ["Mohamed Hamaki", "محمد حماقي"], ["Ahmed Saad", "أحمد سعد"], ["Assala", "أصالة"],
    ["Sherine", "شيرين"], ["Angham", "أنغام"], ["Nancy Ajram", "نانسي عجرم"], ["Elissa", "إليسا"],
    ["Haifa Wehbe", "هيفاء وهبي"], ["Nawal El Zoghbi", "نوال الزغبي"], ["Wael Kfoury", "وائل كفوري"],
    ["Ragheb Alama", "راغب علامة"], ["Kazem Al Saher", "كاظم الساهر"], ["Cheb Khaled", "الشاب خالد"],
    ["Saad Lamjarred", "سعد لمجرد"], ["Balqees", "بلقيس"], ["Dina Hayek", "دينا حايك"],
    ["Myriam Fares", "ميريام فارس"], ["Hamada Helal", "حماده هلال"], ["Mostafa Amar", "مصطفى قمر"],
    ["Mohamed Mounir", "محمد منير"], ["Ali El Haggar", "علي الحجار"], ["Hakim", "حكيم"],
    ["Shaaban Abdel Rahim", "شعبان عبد الرحيم"], ["Saad El Soghayar", "سعد الصغير"],
    ["Bosy", "بوسي"], ["Hisham Abbas", "هشام عباس"], ["Amir Eid", "أمير عيد"],
    ["Cairokee", "كايروكي"], ["Wust El Balad", "وسط البلد"], ["Massar Egbari", "مسار إجباري"],
    ["Aziz Maraka", "عزيز مرقة"], ["Yara", "يارا"], ["Diana Karazon", "ديانا كرزون"],
    ["Maher Zain", "ماهر زين"], ["Humood Alkhudher", "حمود الخضر"], ["Wegz", "ويجز"],
    ["Marwan Pablo", "مروان بابلو"], ["Marwan Moussa", "مروان موسى"], ["Abyusif", "أبيوسف"],
    ["Molotof", "مولوتوف"], ["Afroto", "أفروتو"], ["Shahyn", "شاهين"], ["Ziad Zaza", "زياد زازا"],
    ["Hamo Bika", "حمو بيكا"], ["Hassan Shakosh", "حسن شاكوش"], ["Omar Kamal", "عمر كمال"],
    ["Perrie", "بيري"], ["Tul8te", "تول8ت"], ["Dalia Mubarak", "داليا مبارك"], ["Adele", "أديل"],
    ["Beyonce", "بيونسيه"], ["Rihanna", "ريهانا"], ["Ed Sheeran", "إد شيران"],
    ["Justin Bieber", "جاستن بيبر"], ["Taylor Swift", "تايلور سويفت"], ["Bruno Mars", "برونو مارس"],
    ["The Weeknd", "ذا ويكند"], ["Drake", "دريك"], ["Shakira", "شاكيرا"],
    ["Enrique Iglesias", "إنريكي إجليسياس"]
  ]
};

export const CATEGORY_META: Record<CategoryKey, { icon: string; key: string }> = {
  players: { icon: '⚽', key: 'catFootball' },
  food: { icon: '🍕', key: 'catFood' },
  places: { icon: '🗺️', key: 'catPlaces' },
  movies: { icon: '🎬', key: 'catMovies' },
  games: { icon: '🎮', key: 'catGames' },
  animals: { icon: '🦁', key: 'catAnimals' },
  jobs: { icon: '💼', key: 'catJobs' },
  singers: { icon: '🎤', key: 'catSingers' }
};

export function getCombinedWordList(categories: CategoryKey[]): [string, string][] {
  let combined: [string, string][] = [];
  categories.forEach(cat => {
    if (wordsDB[cat]) combined = combined.concat(wordsDB[cat]);
  });
  if (combined.length === 0) combined = wordsDB.players;
  return combined;
}
